
IS_DEBUG = True

BLOCK_SIZE = 50

SCREEN_WIDTH = 1300
SCREEN_HEIGHT = 1100

HALF_SCREEN_WIDTH = SCREEN_WIDTH // 2
HALF_SCREEN_HEIGHT = SCREEN_HEIGHT // 2

GAME_FIELD_WIDTH = SCREEN_WIDTH // BLOCK_SIZE
GAME_FIELD_HEIGHT = SCREEN_HEIGHT // BLOCK_SIZE
